"""Added age column to product

Revision ID: 288677264e70
Revises: ca2418b6ddf9
Create Date: 2020-12-27 14:40:14.629457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '288677264e70'
down_revision = 'ca2418b6ddf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'image')
    # ### end Alembic commands ###
