"""add is_customer

Revision ID: fa7933180a48
Revises: 288677264e70
Create Date: 2020-12-27 22:02:00.576120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa7933180a48'
down_revision = '288677264e70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_customer', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_customer')
    # ### end Alembic commands ###
